# Generated by Django 3.0.5 on 2021-10-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('batting_hand', models.CharField(choices=[('Left hand bat', 'Left hand bat'), ('Right hand bat', 'Right hand bat')], max_length=100)),
                ('bowling_hand', models.CharField(choices=[('Left Arm Fast', 'Left Arm Fast'), ('Right Arm Medium', 'Right Arm Medium'), ('Right Arm Fast', 'Right Arm Fast'), ('Left Arm Medium', 'Left Arm Medium'), ('Right Arm Offbreak', 'Right Arm Offbreak'), ('Left Arm Offbreak', 'Left Arm Offbreak')], max_length=100)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All rounder', 'All rounder')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country')),
                ('player', models.ManyToManyField(blank=True, related_name='Team_player_name', to='api.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('Venue', models.CharField(max_length=100)),
                ('bowler_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler_of_match_id', to='api.Player')),
                ('man_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_of_match_id', to='api.Player')),
                ('match_lose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_lose_id', to='api.Team')),
                ('match_win_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_win_id', to='api.Team')),
                ('opponent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_team_id', to='api.Team')),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_id', to='api.Team')),
                ('toss_lose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_toss_lose_id', to='api.Team')),
                ('toss_win_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_toss_win_id', to='api.Team')),
            ],
        ),
    ]
